# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-
top = '../..'

def build(bld):
    bld.objects(
        target='ndndataservice-objects',
        source=bld.path.ant_glob('ndndataservice/*.cpp', excl='ndndataservice/main.cpp'),
        use='core-objects')

    bld.program(
        target='../../bin/ndndataservice',
        name='ndndataservice',
        source='ndndataservice/main.cpp',
        use='ndndataservice-objects')

    bld.objects(
        target='ndndataclient-objects',
        source=bld.path.ant_glob('ndndataclient/*.cpp', excl='ndndataclient/main.cpp'),
        use='core-objects')

    bld.program(
        target='../../bin/ndndataclient',
        name='ndndataclient',
        source='ndndataclient/main.cpp',
        use='ndndataclient-objects')

    ## (for unit tests)

   ## bld(target='peek-objects',
   ##     use='ndnpeek-objects ndnpoke-objects')
